apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  credentials: YXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBWFFITE5ZNFdKV0c1UDRYVQphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSByYWZKbVI3K0FuNTM4K2prSTI3dmVYL0Z3WkRabHJVTk54YlBkYjI3Cg==